export const ROUTE_TITLE_MAP = {
  Dashboard: 'Dashboard',
  Login: 'Login',
  Forbidden: 'Akses Ditolak',
  RawMaterials: 'Bahan Baku',
  Products: 'Produk',
  Suppliers: 'Supplier',
  Customers: 'Pelanggan',
  Salesmen: 'Sales',
  Positions: 'Jabatan',
  Employees: 'Karyawan',
  Units: 'Satuan',
  ChartOfAccounts: 'Daftar Akun',
  Roles: 'Peran',
  Users: 'Pengguna',
  PurchaseRequests: 'Permintaan Pembelian',
  PurchaseOrders: 'Pembelian',
  GoodsReceipts: 'Penerimaan Barang',
  PurchasePayments: 'Pembayaran Pembelian',
  Sales: 'Penjualan',
  SalePayments: 'Pembayaran Penjualan',
  CashTransactions: 'Transaksi Kas',
  Journals: 'Jurnal',
  StockAdjustments: 'Penyesuaian Stok',
  StockMovements: 'Mutasi Stok',
  MaterialIssuesList: 'Pengeluaran Bahan Baku',
  ProductionPlansList: 'Rencana Produksi',
  ProductionRealizationsList: 'Realisasi Produksi',
  FinishedGoodsReceiptsList: 'Penerimaan Barang Jadi',
  ProfitLoss: 'Laporan Laba Rugi',
  Payables: 'Laporan Hutang',
  Receivables: 'Laporan Piutang',
  Ledger: 'Buku Besar',
  RawMaterialStockCard: 'Kartu Stok Bahan Baku',
  StockOpnameReport: 'Laporan Stok Opname',
  PurchaseOrderRecap: 'Laporan Rekap Pembelian',
  SupplierPayableStatement: 'Kartu Hutang Supplier',
  FinishedGoodsStockOpname: 'Laporan Stok Opname Barang Jadi',
  FinishedGoodsMonthlyStock: 'Laporan Stok Bulanan Barang Jadi',
  MaterialIssueMonthlyReport: 'Laporan Pengeluaran Bahan Baku',
  ProductionReport: 'Laporan Produksi',
  RawMaterialStockCardPrint: 'Cetak Kartu Stok Bahan Baku',
  StockOpnameReportPrint: 'Cetak Laporan Stok Opname',
  PurchaseOrderRecapPrint: 'Cetak Laporan Rekap Pembelian',
  FinishedGoodsStockOpnamePrint: 'Cetak Laporan Stok Opname Barang Jadi',
  FinishedGoodsMonthlyStockPrint: 'Cetak Laporan Stok Bulanan Barang Jadi',
  MaterialIssueMonthlyPrint: 'Cetak Laporan Pengeluaran Bahan Baku',
  MaterialIssuePrint: 'Cetak Pengeluaran Bahan Baku',
  ProductionReportPrint: 'Cetak Laporan Produksi',
}

export const STATUS_LABEL_MAP = {
  DRAFT: 'Draft',
  APPROVED: 'Disetujui',
  CANCELLED: 'Dibatalkan',
  REJECTED: 'Ditolak',
  SUBMITTED: 'Diajukan',
  ACTIVE: 'Aktif',
  INACTIVE: 'Nonaktif',
  PAID: 'Lunas',
  UNPAID: 'Belum Dibayar',
  OPEN: 'Terbuka',
  CLOSED: 'Ditutup',
  PENDING: 'Menunggu',
  COMPLETED: 'Selesai',
  PARTIAL: 'Sebagian',
  RECEIVED: 'Diterima',
  OVERDUE: 'Jatuh Tempo',
  BELUM_DIREALISASI: 'Belum Direalisasi',
  SESUAI_TARGET: 'Sesuai Target',
  UNDER_TARGET: 'Di Bawah Target',
  OVER_TARGET: 'Melebihi Target',
  IN: 'Masuk',
  OUT: 'Keluar',
}
